#!/bin/bash

function noyes {
  echo -n "$1 [N/Y]:"
  read a
  if [[ "$a" == "N" ||  "$a" == "n" || "$a" == "" ]]; then
     return 0
  fi
  return 1
}

function log_msg {
  RED=$(tput setaf 1)
  GREEN=$(tput setaf 2)
  NORMAL=$(tput sgr0)
  MSG="$1"
  STATUS="[OK]"
  STATUSCOLOR="$GREEN${STATUS}$NORMAL"
  let COL=$(tput cols)-${#MSG}+${#STATUSCOLOR}-${#STATUS}

  echo -n $MSG
  printf "%${COL}s\n"  "$STATUSCOLOR"
}

##
# 1 repo
# 2 user
# 3 folder
# 4 ssh|http|git

function git_get {
  echo "Cloning $1 from Github..."
  if [[ "$4" == "ssh"  ]]; then
    git clone -q "git@github.com:$2/$1.git" "$3"
  elif [[ "$4" == "git" ]]; then
    git clone -q "git://github.com/$2/$1.git" "$3"
  else 
    git clone -q "https://$2@github.com/$2/$1.git" "$3"
  fi
}

function installed {
  if [[ "$2" == "no_msg" ]]; then
    type $1 >/dev/null 2>&1 && return 0 || return 1 
  else
    type $1 >/dev/null 2>&1 && log_msg "$1 is installed already" && return 0 || return 1 
  fi
}

###
# Get Github name for user specific clones 
###
function get_github_name {
  if [[ -z $github_name ]]; then
    printf "Enter your Github user name:"
    read -r github_name
    if [[ -z $github_name ]]; then
      return 1
    fi
  fi
  echo "Your Github name is: $github_name"
  return 0
}

###
# Create my default folder structures
#
function pre_install {
  mkdir "$HOME/bin"
  mkdir "$HOME/tmp"
  mkdir "$HOME/usr"
  mkdir "$HOME/usr/local"
  mkdir "$HOME/src"
  mkdir "$HOME/src/github"
  mkdir "$HOME/src/aur"
  mkdir "$HOME/imports"
  mkdir "$HOME/exports"
}

##
# 1 github repo
# 2 directory to install
function dot_folder_install {
    display_menu "github"
    get_github_name
    
    repo=$1
    dir=$2
    app_dir="$HOME/$dir"
    # don't install twice
    if ! [ -d "$app_dir" ]; then
        git_get $repo $github_name $app_dir "git"
    else
        return 1
    fi
    return 1
}

##
# 1 str
# 2 array
function containsElement {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}