#!/bin/bash

if [ -L $0 ]; then
  WD=$(dirname "$(readlink -f $0)")
else
  WD=$(dirname $0)
fi

pushd $WD

PM="pacman"
PM_INSTALL="$PM -S --needed"

. funcs
. apps
. menus

function run_install {
    pre_install
    CMD="$1_install"
    $CMD
}

until [ "$to_install" = "exit" ]; do
    display_menu "install"
    printf "pick:"
    read -r to_install

    case $to_install in
        core | extra | webdev | comp | all )
            run_install $to_install
            ;;
        exit )
            log_msg "exit"
            ;;
        * )
            log_msg "Not Vaild Group"
            ;;
    esac
done

 log_msg "Fin." 

