#!/bin/bash

cat << _EOF_

###############################################################################
#                                                                             #
#  You should have all the features you wish to install                       #
#  forked on your github profile                                              #
#                                                                             #
###############################################################################

_EOF_

exec 3<&0

function noyes {
  echo -n "$1 [N/Y]:"
  read a <&3
  if [[ "$a" == "N" ||  "$a" == "n" || "$a" == "" ]]; then
     return 0
  fi
  return 1
}

function log_msg {
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    NORMAL=$(tput sgr0)
    MSG="$1"
    STATUS="[OK]"
    STATUSCOLOR="$GREEN${STATUS}$NORMAL"
    let COL=$(tput cols)-${#MSG}+${#STATUSCOLOR}-${#STATUS}

    echo -n $MSG
    printf "%${COL}s\n"  "$STATUSCOLOR"
}

function git_get_feature {
  echo "Cloning $1 from Github..."
  git clone -q "git://github.com/$github_name/$1.git" "$HOME/$2"
}

function get_app {
  noyes "Install $2?" && return 0
  if [[ $1 == "git" ]]; then
    git_get_feature $2 $3
  elif [[ $1 == "apt" ]]; then
    sudo apt-get install $2 -y
  fi
  
  if [[ "$3" != "-" && "$4" != "-" ]]; then
    HERE=$(pwd)
    cd "$HOME/$3"
    sudo $4
    cd $HERE
  fi
 return 1
}

function should_install {
    type $1 >/dev/null 2>&1 && log_msg "$1 is installed already" || get_app $2 $1 $3 $4
}

echo -n "Enter your Github user name:"
read github_name

echo "Your Github name is: $github_name"

while read line; do
  first=${line%% *}
  line=${line#* }
  sec=${line%% *}
  line=${line#* }
  third=${line%% *}
  line=${line#* }
  fourth=${line%% *}

  should_install $first $sec $third $fourth
  
done < "install_list"

log_msg "Fin." 

