#!/bin/bash

function display_menu {
if [[ "$1" == "github" ]]; then
cat << _EOF_

###############################################################################
#                                                                             #
#  Github user profile to use when cloning repos                              #
#                                                                             #
###############################################################################

_EOF_
elif [[ "$1" == "install" ]]; then
cat << _EOF_

###############################################################################
#                                                                             #
#  Pick Install group                                                         #
#  core: Core programs and terminal configurations                            #
#  extra: We are getting stylish                                              #
#  webdev: PHP nodejs and python                                              #
#  comp: software compilation packages                                        #
#  all: All of the above                                                      #
#  exit: Get me out of here                                                   #
#                                                                             #
###############################################################################

_EOF_
fi

}

